pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://files.minecraftforge.net/maven/' }
        maven{url='https://maven.blamejared.com/'}
        gradlePluginPortal()
    }
}

rootProject.name = 'almightly_staff'

include 'common'
include 'fabric'
include 'forge'
