
plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.0.0'
}
repositories {

    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.hexxy.media" }
    maven { url = "https://maven.blamejared.com/" }
    maven { url = "https://maven.jamieswhiteshirt.com/libs-release/" }
    maven { url = "https://maven.kosmx.dev/" }
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.terraformersmc.com/releases" }
    maven { url = "https://maven.ladysnake.org/releases" }
    maven { url = "https://mvn.devos.one/snapshots/" }
    mavenCentral()
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {

    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    modImplementation "at.petra-k.hexcasting:hexcasting-common-1.20.1:$rootProject.hexcasting_version"
    modApi "me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_version}"
    //compileOnly "vazkii.patchouli:Patchouli-xplat:$minecraft_version-$patchouli_version-SNAPSHOT"
    //compileOnly ("maven.modrinth:patchouli:${minecraft_version}-${patchouli_version}-forge")
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    //modImplementation fileTree(dir: "libs", include: '*.jar')
}
compileKotlin {
    kotlinOptions {
        jvmTarget = "17"
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "17"
    }
}
